### ISSUE TITLE
Feature Request: Code Wrapping in Editing Mode

### ISSUE THREAD

**Issue by mayurankv** [mayurankv/Obsidian-Code-Styler#12]
## Summary

Add code wrapping options in editing mode.

### Basic example

Similar to how they are done in reading mode. The whole codeblock should scroll though, not individual lines.

### Motivation

More usable codeblocks in edit mode.

## Existing Requests?

No existing requests.

**Comment by mayurankv** [comment]
Consider this css I have used in the past. Scrolling document could be ok as long as codeblock covers length of code.

```css
/*! Wrap Live Preview Codeblock */
.HyperMD-codeblock:not(.cm-active):not(:hover) > .cm-hmd-codeblock {
    white-space: nowrap !important;
}
.markdown-source-view.mod-cm6 .block-language-preview code {
    white-space: pre-wrap !important;
}
```

**Comment by mayurankv** [comment]
> Wrapping in editor requires `EditorView.lineWrapping` extension
> https://discuss.codemirror.net/t/word-wrapping/4512
> 
> ```typescript
new EditorView({
    state: EditorState.create({
        extensions: [
            EditorView.lineWrapping
        ]
    })
})
> ```

**Comment by mayurankv** [comment]
Unfortunately, this doesn't help editor wrapping since the default is already wrap. Implementing unwrap is the issue (as well as active unwrap). The only way to implement this currently that I can envisage is setting `nowrap` similar to the above snippets and extending the codeblock visually to cover the unwrapped lines.

The issues with this approach are:
- Scrolls the whole document which is a bit weird (but better than scrolling individual lines)
- How do you know how far to extend the background for the unwrapped lines?
- Can you actually visually extend the codeblock in this way

**Comment by mayurankv** [comment]
Template css:

```css
.HyperMD-codeblock:has(> .cm-widgetBuffer) > .cm-hmd-codeblock {
    white-space: nowrap !important;
}

.code-styler-line {
    overflow: visible !important;
}

.code-styler-line.HyperMD-codeblock-end {
    overflow: hidden !important
}

.code-styler-line::after {
    content: "";
    background: red;
    position: absolute;
    top: 0;
    bottom:0;
    left:0;
    right: -100px;
    z-index: -1;
}
```
