### ISSUE TITLE
Bug: Active line not highlighted when codeblock language is specified

### ISSUE THREAD

**Issue by alythobani** [mayurankv/Obsidian-Code-Styler#288]
## Describe the bug

The active line highlighting in a codeblock only works if the codeblock doesn't have a language specified. (CSS bug)

### Steps to reproduce

1. Enable "Codeblock Active Line Highlight"
2. Create a codeblock, and specify a language e.g. `ts`
3. Place cursor inside codeblock, and observe that the active line does not get highlighted

### Example codeblock
````markdown
```ts
test
```
````

### Expected behaviour

Active line should be highlighted the way it is when a language isn't specified:

<img width="767" alt="Screen Shot 2024-10-14 at 1 12 02 PM" src="https://github.com/user-attachments/assets/eea9ab5b-764e-4f64-bec0-40c14ee93fca">

### Current behaviour

Active line is not highlighted when language is specified:
<img width="703" alt="Screen Shot 2024-10-14 at 1 12 24 PM" src="https://github.com/user-attachments/assets/c96186d7-b2f9-4921-a839-089f0fc5dcf8">

### Environment

- Plugin Version: 1.1.7
- Obsidian Version:  1.6.7
- Platform:  Desktop
- OS:  Mac - Monterey 12.5
- Theme:  default
- CSS Snippets:  no

### Additional context / Possible solution

Experimenting a little with the source code in `codeblocks.css`, it looks like the `background` property from lines 309-312:

```css
.code-styler-active-line-highlight .markdown-source-view .HyperMD-codeblock.cm-active,
.code-styler-active-line-highlight-codeblock .markdown-source-view .HyperMD-codeblock.cm-active {
	background: linear-gradient(to right, var(--code-styler-active-codeblock-line-colour), var(--gradient-highlights-colour-stop), var(--code-styler-codeblock-background-colour)) !important;
}
```

is getting overridden by the `background` property from lines 143-145:

```css
.code-styler .markdown-source-view .HyperMD-codeblock[class*='code-styler-line'][class*='language-'] {
	background: linear-gradient(90deg, var(--language-border-colour), var(--language-border-colour) var(--language-border-width), var(--gradient-background-colour) var(--language-border-width) var(--gradient-highlights-colour-stop), transparent 100%), var(--code-styler-codeblock-background-colour) !important;
}
```

And changing lines 309-312 to just set `--gradient-background-colour` ( instead of `background` fixes things. Albeit not fully perfectly: the active line highlighting then fully overrides any other line highlighting e.g. `hl`; whereas maybe ideally they'd overlap so it's still clear that the current line has another highlight underneath.

<img width="744" alt="Screen Shot 2024-10-14 at 2 49 38 PM" src="https://github.com/user-attachments/assets/d08dd846-d81a-4414-9e81-76a27e398866">
<img width="749" alt="Screen Shot 2024-10-14 at 2 49 43 PM" src="https://github.com/user-attachments/assets/44a84503-0106-4d9c-867e-5f9d59c031a8">

But this is probably good enough as a quick initial fix (a better/different fix, where the active highlighting would be layered on top of other highlighting, might involve a deeper change to the implementation, e.g. maybe adding another `div` layer for the `hl` highlighting).

Very cool plugin btw :)
