### ISSUE TITLE
Bug: Add option to disable Copy button, cuz it have conflict with theme and builtin feature

### ISSUE THREAD

**Issue by Kol9yN** [mayurankv/Obsidian-Code-Styler#303]
### Steps to reproduce

Hover cursor on copy button

Yes

````markdown
```mysql
select * from user\G
```
````

### Expected behavior

Appears on hover and stay

### Current behavior

Glitching

### Environment

- Plugin Version: 
- 1.1.7
- Obsidian Version:  
- 1.7.7
- Platform:  
- Desktop
- OS:  
- Win
- Theme:  
- Phoenix, Default
- CSS Snippets:  
- Disabled

### Screenshots

https://github.com/user-attachments/assets/79594dbb-e468-477e-b213-139adaa389fc

### Additional context

No

**Comment by mayurankv** [comment]
Currently refactoring the plugin! Nearly done! This should be fixed soon. Sorry for the issue! As a temporary workaround you can find the button in a css selector and add display:none if you are confident.

**Comment by Kol9yN** [comment]
Please, i propose, if it possible, add option to disable plugin Copy button, cuz Obsidian have own without sliding animation, and i think, it looks more convenient

**Comment by mayurankv** [comment]
I am currently upgrading the plugin as I mentioned. Obsidian updated the copy button since I last updated this plugin so the styling doesn't appear to work anymore. I will indeed be upgrading it to match the default setting, and will do this through as little markup as possible, but I want the preview and reading mode copy buttons to look the same which they don't at all in default obsidian. I hope that makes sense.

**Comment by mayurankv** [comment]
What I mean to say is it's unlikely I'll completely leave the default copy button, but I will try and do as minimal changes to make them appear consistent in both live preview and reading mode. I do plan on removing the sliding feature though!

**Comment by MrSergioRodrigo** [comment]
@mayurankv I'm also waiting for this issue to be resolved. I'm not sure how to temporarily disable this button using CSS. Could you please explain?

**Comment by lasterX** [comment]
I wrote this CSS code snippet, it's useful for me. Hope it helps you. @Kol9yN @MrSergioRodrigo 
```
/* remove "code-styler" copy button  */
body pre.code-styler-pre:has(.code-styler-header-container-hidden) button.copy-code-button, 
body .markdown-source-view :not(pre.code-styler-pre) > .code-styler-header-container-hidden + .HyperMD-codeblock-begin span.code-block-flair{
  display: none !important; 
}
```
Obsidian version: 1.8.7
theme: minimal

**Comment by MrSergioRodrigo** [comment]
@lasterX Thanks, but unfortunately it didn't work for me.
If I use this snippet, the copy buttons disappear altogether.

I tried the same version as you have 1.8.7, and even tried to put the theme minimal

**Comment by Kol9yN** [comment]
i think just need to wait until project owner rework it

**Comment by mayurankv** [comment]
Hi sorry, I recently started a new job and haven't had the time to complete the refactor which solves this issue, will try and get back to it soon :((

**Comment by Reydan46** [comment]
While the author hasn't rushed to fix this issue yet, you can use this workaround:

```css
/* Position the Code Styler copy button a bit left inside embed blocks
   so it does not overlap with the built-in "open" (expand) icon */
.internal-embed .code-styler-pre-parent .copy-code-button {
    right: 20px;
}

/* Disable Code Styler's hover animation and sliding badge,
   keep the button visually stable on hover */
pre.code-styler-pre button.copy-code-button:hover, pre.code-styler-pre button.run-code-button:hover, .markdown-source-view.mod-cm6 .HyperMD-codeblock.code-styler-line span.code-block-flair:hover {
    margin-right: calc(var(--copy-code-header-right-margin) - var(--dent-difference));
    animation: unset;
    clip-path: polygon(0 0, 16px 0, 16px 36px, 0 36px);
}

/* Turn off idle animations and set a base opacity
   for copy/run buttons and the flair badge */
pre.code-styler-pre button.copy-code-button:not(:active), pre.code-styler-pre button.run-code-button:not(:active), .markdown-source-view.mod-cm6 .HyperMD-codeblock.code-styler-line span.code-block-flair:not(:active) {
    animation: unset;
    opacity: .7;
    transition: opacity .1s linear;
}

/* On hover just increase opacity instead of running
   the original Code Styler hover animation */
pre.code-styler-pre button.copy-code-button:not(:active), pre.code-styler-pre button.run-code-button:not(:active), .markdown-source-view.mod-cm6 .HyperMD-codeblock.code-styler-line span.code-block-flair:not(:active):hover {
    opacity: 1;
}

/* Hide the textual "Copy" badge / tooltip that appears on hover
   so it does not push or overlap other icons */
.markdown-source-view.mod-cm6 .HyperMD-codeblock.code-styler-line span.code-block-flair::after {
    visibility: hidden;
}

/* Adjust spacing between the pseudo-icon/text and the rest of the header */
pre.code-styler-pre button.copy-code-button::before, .markdown-source-view.mod-cm6 .HyperMD-codeblock.code-styler-line span.code-block-flair::before {
    padding-right: 4px;
}

/* Hide the SVG copy icon inside the Code Styler copy button
   (you rely on text / ::before instead) */
pre.code-styler-pre button.copy-code-button svg.svg-icon.lucide-copy {
    visibility: hidden;
}
```

<img width="825" height="374" alt="Image" src="https://github.com/user-attachments/assets/8c188b02-0ff3-4b61-b4ee-e5d583354089" />
