### ISSUE TITLE
Bug: Compatibility with "Blur" plugin

### ISSUE THREAD

**Issue by Aetherinox** [mayurankv/Obsidian-Code-Styler#97]
## Describe the bug
Code Styler css properties are conflicting with another plugin called **[Blur](https://github.com/gapmiss/blur)**. It is causing two of the three code blocks to be visible at all times no matter what.

You have one particular CSS property that is causing all the blocks to be revealed:

```css
.code-styler .cm-s-obsidian span.cm-inline-code,
.code-styler .markdown-rendered :not(pre) > code {
  padding: var(--code-styler-inline-padding-vertical) var(--code-styler-inline-padding-horizontal) !important;
  border-radius: var(--code-styler-inline-border-radius) !important;
  margin: 0px var(--code-styler-inline-margin-horizontal) !important;
  background-color: var(--code-styler-inline-background-colour) !important;
  color: var(--code-styler-inline-colour);
  font-weight: var(--code-styler-inline-font-weight);
}
```

In order to temporarily correct the issue, I had to modify the Code Styler's css because everything is marked as `!important` and I can't get anything to override with my own custom CSS file. The code in your stylesheet was replaced with:

```css
.code-styler .cm-s-obsidian span.cm-inline-code, 
.code-styler .markdown-rendered :not(pre) > code:not(.blur-brick):not(.blur-bone):not(.blur-inline) {
  padding: var(--code-styler-inline-padding-vertical) var(--code-styler-inline-padding-horizontal) !important;
  border-radius: var(--code-styler-inline-border-radius) !important;
  margin: 0px var(--code-styler-inline-margin-horizontal) !important;
  background-color: var(--code-styler-inline-background-colour) !important;
  color: var(--code-styler-inline-colour);
  font-weight: var(--code-styler-inline-font-weight);
}
```

I'm sure there's probably a better way to do it, but I've tried for about an hour, and I can't seem to override and allow both plugins to work properly.

### Steps to reproduce

- Install your Code Styler Plugin
- Install [Blur](https://github.com/gapmiss/blur)
- Create a test codeblock:

````markdown

```blur
Alpha Bravo Charlie Delta Echo Foxtrot Golf
```

```blur-brick
Alpha Bravo Charliez Delta Echo Foxtrot Golf
```

```blur-bone
Alpha Bravo Charlie Delta Echo Foxtrot Golf
```
````

### Expected behaviour

Any text inside the `blur` code boxes should be censored / blacked out

### Current behaviour

Text in block `blur` works as it should, however, the text inside `blur-brick` and `blur-bone` shows at all times until the above edit is made to the Code Styler CSS.

### Environment

- Plugin Version: **v1.0.7**
- Obsidian Version:  **v1.3.7**
- Platform:  **Desktop**
- OS:  **Windows 11 Pro**
- Theme:  **Blue Topaz**
- CSS Snippets:  No

### Screenshots

Your CSS property is causing the plugin text blocks to appear as:
![RCcHTMt](https://github.com/mayurankv/Obsidian-Code-Styler/assets/118329232/01458319-a753-4106-a410-b0c5be5c64f7)

The blur plugin should make text appear as:
![GfHkUjF](https://github.com/mayurankv/Obsidian-Code-Styler/assets/118329232/3676f463-94a4-43d0-8502-c59ee554d862)

### Additional context

Per the instructions on the official github for [Blur](https://github.com/gapmiss/blur), if you want to be able to hover each block and have the text become visible, you must:

- Install https://github.com/mgmeyers/obsidian-style-settings
- Create a new custom stylesheet snippet named `obsidian-blur-plugin.css` in `/path/to/vault/.obsidian/snippets`
- Paste the following code inside:
```css
/* @settings

name: Blur Plugin
id: obsidian-blur
settings:
-
  id: obsidian-blur-hover
  title: Reveal obfuscated text on mouse hover
  type: class-toggle
  default: false
-
  id: obsidian-blur-filter
  title: Blur filter strength
  type: variable-text
  default: 5px
-
  id: obsidian-blur-brick-color
  title: Brick color
  type: variable-themed-color
  format: hsl
  opacity: true
  default-light: 'hsla(220,19%,6%,1)'
  default-dark: 'hsla(220,100%,100%,1)'
-
  id: obsidian-blur-brick-border-radius
  title: Brick border-radius
  type: variable-text
  default: 1px
-
  id: obsidian-blur-brick-line-height
  title: Brick line-height
  type: variable-number-slider
  default: 1
  min: 1
  max: 2
  step: .05
- 
  id: obsidian-blur-bone-color
  title: Bone color
  type: variable-themed-color
  format: hsl
  opacity: true
  default-light: 'hsla(220,19%,6%,1)'
  default-dark: 'hsla(220,100%,100%,1)'
-
  id: obsidian-blur-bone-border-radius
  title: Bone border-radius
  type: variable-text
  default: 1.5em
-
  id: obsidian-blur-bone-line-height
  title: Bone line-height
  type: variable-number-slider
  default: 1
  min: 1
  max: 2
  step: .05
-
*/
```
- Enable snippet under **Settings** > **Appearance** > **CSS snippets**
- Open `Style Sheets` plugin in Obisidian
- Click the `Blur` dropdown
- **Enable** `Reveal obfuscated text on mouse hover`
